#version: "2"
services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./www/html/:/var/www/html/

  php:
    build: ./php/
    container_name: php-container
    # expose: 
      # – 9000:9000
    volumes_from:
      - app-data

  app-data:
    image: php:8.1-fpm
    container_name: app-data-container
    volumes:
      - ./www/html/:/var/www/html/
    command: "true"

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    volumes_from:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass

  mysql-data:
    image: mysql:5.7
    container_name: mysql-data-container
    volumes:
      - ./mysql/:/var/lib/mysql/
    command: "true"